name: Build Docker images

on:
    push:
        branches: ["main", "develop"]
        paths:
            - "apps/api/**"

jobs:
    build-and-push-dockerfile-image:
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: ${{ secrets.API_DATABASE_URL }}
            BETTER_AUTH_SECRET: ${{ secrets.API_BETTER_AUTH_SECRET }}
            BETTER_AUTH_URL: ${{ secrets.API_BETTER_AUTH_URL }}
            CLIENT_ORIGIN: ${{ secrets.API_CLIENT_ORIGIN }}
            GOOGLE_CLIENT_ID: ${{ secrets.API_GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.API_GOOGLE_CLIENT_SECRET }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }} # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret
                  password: ${{ secrets.DOCKERHUB_TOKEN }} # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      satriadhikara/jejak-api:latest
                  platforms: linux/amd64
